In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn import preprocessing


veriler = pd.read_csv('data.csv')
dummy_degiskenler = pd.get_dummies(veriler['ulke'],dtype='int')

dummy_degiskenler.columns = ['fr', 'tr', 'us']  

veriler = pd.concat([veriler, dummy_degiskenler], axis=1)
veriler.pop('ulke')
veriler['cinsiyet'] = (veriler['cinsiyet'] == 'e').astype(int)
veriler.dropna(inplace=True)

cinsiyet =  veriler.pop('boy')

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression



import statsmodels.api as sm
print(veriler)
print(veriler.values)
X = veriler.values 
X = np.append(arr=np.ones((X.shape[0], 1)).astype(int), values=X, axis=1)  
X = np.delete(X,2,axis=1)
linear = LinearRegression()
x_train, x_test, y_train, y_test = train_test_split(veriler, cinsiyet)
linear.fit(x_train,y_train)
y_pred = linear.predict(x_test)
sm_model = sm.OLS(cinsiyet,X).fit()
print(sm_model.summary())


/usr/local/lib/python3.10/dist-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


    kilo  yas  cinsiyet  fr  tr  us
0     30   10         1   0   1   0
1     36   11         1   0   1   0
2     34   10         0   0   1   0
3     30    9         0   0   1   0
4     38   12         1   0   1   0
5     90   30         1   0   1   0
6     80   25         1   0   1   0
7     90   35         1   0   1   0
8     60   22         0   0   1   0
9    105   33         1   0   0   1
10    55   27         0   0   0   1
11    50   44         0   0   0   1
12    58   39         0   0   0   1
13    59   41         0   0   0   1
14    62   55         0   0   0   1
15    70   47         1   1   0   0
16    90   23         1   1   0   0
17    80   27         1   1   0   0
18    88   28         1   1   0   0
19    40   29         0   1   0   0
20    66   32         0   1   0   0
21    56   42         0   1   0   0
[[ 30  10   1   0   1   0]
 [ 36  11   1   0   1   0]
 [ 34  10   0   0   1   0]
 [ 30   9   0   0   1   0]
 [ 38  12   1   0   1   0]
 [ 90  30   1   0   1   0]
 [ 80  25 